// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bleswtkoafdljurmythi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsZXN3dGtvYWZkbGp1cm15dGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4Mzk5NTUsImV4cCI6MjA3MzQxNTk1NX0.f_TLDmwTMavpSEfRqbvQRiLkgwrauX1GNrhcOkr2APE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});